[Settings]
  siteId="0bc44268-2f0c-4380-a0ac-55d7d97b9729"

[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "14" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
